spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionestudiantil
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # Cambia 'create-drop' a 'update' para no perder datos

camunda:
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.bpmn20.xml
    - classpath*:**/*.dmn
    - classpath*:**/*.dmn11.xml
    - classpath*:**/*.form
  bpm:
    database:
      type: postgres
    schema-update: true
    job-execution:
      enabled: true
    webapp:
      enabled: true
    admin-user:
      id: demo  # Crear un usuario administrador con ID 'demo'
      password: demo  # Password para el usuario administrador
    rest:
      enabled: true  # Asegúrate de que la API REST esté habilitada
