spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionestudiantil #Para ejecuciones locales
#    url: jdbc:postgresql://postgresql:5432/gestionestudiantil #Para ejecuciones de docker
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # O 'update' para mantener los datos

camunda:
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.bpmn20.xml
    - classpath*:**/*.dmn
    - classpath*:**/*.dmn11.xml
    - classpath*:**/*.form
  bpm:
    enforce-history-time-to-live: false  # Desactiva la verificación de TTL (usar solo para pruebas)
    database:
      type: postgres
    schema-update: true
    job-execution:
      enabled: true
    webapp:
      enabled: true
    admin-user:
      id: demo
      password: demo
    rest:
      enabled: true